Enable Mak RTI use
openlvc/disco pull request #47
Opened 2021-04-19 05:42 UTC by jarrodgreene

Mak RTI 4.4 can now be selected as an option for HLA networking
in both CNR-Sim and CNR-Touch in the same manner Pitch or Portico
can be used.

Mak required several work-arounds due to being C based rather than
Java based.
- module files located in a jar need to be extracted to a regular file.
- Mak's dependencies had to be added to the library path rather than the classpath

Working CNR-1963

2021-04-21 07:09 UTC, timpokorny requested changes
Looks good, just with some small changes to shuffle things around.

2021-04-21 07:09 UTC, timpokorny commented on codebase/src/java/disco/org/openlvc/disco/OpsCenter.java
> +		}
@jarrodgreene This looks fine, but can we move this into a method inside the `ClassLoaderUtils` class and just reference it here? (like the standard classpath extension). Means we can keep all the ugly reflection stuff in the one spot.

2021-04-21 07:09 UTC, timpokorny commented on codebase/src/java/disco/org/openlvc/disco/configuration/RprConfiguration.java
> +		Mak("C:/MAK/makRti4.4", "lib/hla.jar" );
Let's change the default path to just `C:/MAK`. It won't be correct, but pretty soon the v4.4 path won't be "correct" either (might already not be the latest). We used to have smarter code that tried to find the path, but it caused other issues. I'm pretty sure the Portico path has similar issues (includes the version in the path). So we might as well be all be wrong.

2021-04-21 07:09 UTC, timpokorny commented on codebase/src/java/disco/org/openlvc/disco/configuration/RprConfiguration.java
> +			throw new DiscoException( "Error loading modules for Mak", e );
Same as above, can we move this to a generic method (in `FileUtils.java` probably?) that will extract a set of relative path names from a generic jar and copy them to an arbitrary location?

2021-04-21 07:09 UTC, timpokorny commented on codebase/src/java/disco/org/openlvc/disco/connection/rpr/RprConnection.java
> +		URL[] createModules = new URL[] { url };
As per comment above, if we can move the FOM module stuff to a generic method in utils and then call it from here.

2021-04-22 04:20 UTC, jarrodgreene commented
@timpokorny I've updated with those changes, although moving the jar extraction stuff into FileUtils I did make a few other changes to the surrounding code as well

2021-05-03 04:58 UTC, timpokorny commented
Merging!

2021-05-03 04:59 UTC, merged